-- ZEVQORA Supabase schema
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz default now()
);
create table if not exists categories (id bigint generated by default as identity primary key,name text unique not null,created_at timestamptz default now());
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null, slug text unique not null, description text, category text, subcategory text,
  brand text, price numeric(12,2) not null, original_price numeric(12,2), discount_percentage numeric(5,2) default 0,
  images jsonb default '[]', rating numeric(2,1) default 0, review_count integer default 0, stock integer default 0,
  sku text unique, specifications jsonb default '{}', variants jsonb default '{}', seller text,
  warranty text, delivery_information text, created_at timestamptz default now()
);
create table if not exists addresses (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,full_name text,phone text,address text,city text,state text,pincode text,created_at timestamptz default now());
create table if not exists cart_items (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,product_id bigint references products(id) on delete cascade,quantity integer not null default 1,unique(user_id,product_id));
create table if not exists wishlist_items (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,product_id bigint references products(id) on delete cascade,unique(user_id,product_id));
create table if not exists orders (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete set null,total_amount numeric(12,2) not null,payment_status text default 'pending',order_status text default 'Pending',cashfree_order_id text,created_at timestamptz default now());
create table if not exists order_items (id bigint generated by default as identity primary key,order_id bigint references orders(id) on delete cascade,product_id bigint references products(id),product_name text,quantity integer,unit_price numeric(12,2));
create table if not exists payments (id bigint generated by default as identity primary key,order_id bigint references orders(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,cashfree_order_id text,cashfree_payment_id text,amount numeric(12,2),currency text default 'INR',status text default 'pending',payment_method text,webhook_status text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists reviews (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,product_id bigint references products(id) on delete cascade,rating integer check(rating between 1 and 5),title text,comment text,image_url text,created_at timestamptz default now(),unique(user_id,product_id));
create table if not exists coupons (id bigint generated by default as identity primary key,code text unique not null,discount_type text,discount_value numeric(12,2),minimum_order numeric(12,2) default 0,maximum_discount numeric(12,2),expiry timestamptz,usage_limit integer,active boolean default true);
create table if not exists notifications (id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete cascade,title text,message text,read boolean default false,created_at timestamptz default now());

alter table profiles enable row level security;
alter table addresses enable row level security;
alter table cart_items enable row level security;
alter table wishlist_items enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table payments enable row level security;
alter table reviews enable row level security;
alter table notifications enable row level security;
